---
title: "MSEApdata"
author:
- name: Atsushi Fukushima
  affiliation: RIKEN Center for Sustainable Resource Science
  email: afukushima@gmail.com
- name: Kozo Nishida
  affiliation: RIKEN Quantitative Biology Center
  email: knishida@riken.jp
output:
  BiocStyle::html_document2:
    toc_float: true
  BiocStyle::pdf_document2: default
package: MSEAp
abstract: |
  Instructions for the MSEAp package.
vignette: |
  %\VignetteIndexEntry{MSEApdata instructions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The `MSEApdata` package is the companion to [`MSEAp`](http://bioconductor.org/packages/MSEAp). It contains the following, which are necessary for metabolite-set enrichment analysis with `MSEAp`:

# Metabolite-set data
`chipenrich::supported_locusdefs()` lists all available locus definitions for `chipenrich::supported_genomes()`.

The `LocusDefinition` class has the following definition:

```{r, eval=FALSE}
methods::setClass("LocusDefinition", methods::representation(
  dframe = "data.frame",
  granges = "GRanges",
  genome.build = "character",
  organism = "character"
),
  package = "chipenrich.data"
);
```

* `nearest_tss`: The locus is the region spanning the midpoints between the TSSs of adjacent genes.
* `nearest_gene`: The locus is the region spanning the midpoints between the boundaries of each gene, where a gene is defined as the region between the furthest upstream TSS and furthest downstream TES for that gene. If two gene loci overlap each other, we take the midpoint of the overlap as the boundary between the two loci. When a gene locus is completely nested within another, we create a disjoint set of 3 intervals, where the outermost gene is separated into 2 intervals broken apart at the endpoints of the nested gene.

# Genesets
`chipenrich::supported_genesets()` lists all available genesets for `chipenrich::supported_genomes()`.

The `GeneSet` class has the following definition:


# Example data for `chipenrich`
We include two example peak sets, `peaks_E2F4` and `peaks_H3K4me3_GM12878`, both for genome hg19.
